---
title: "Information on prediction models"
output: rmarkdown::html_vignette
author: Henning Teickner
date: "`r Sys.Date()`"
vignette: >
  %\VignetteIndexEntry{irpeatmodels-models}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
bibliography: '../inst/REFERENCES.bib'
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

```{r setup, echo=FALSE, include=FALSE}
library(irpeat)
library(kableExtra)
```


# Introduction

This vignette provides high-level information on the prediction models used in 'irpeat'. In particular, this information can be used to decide if a model is suitable for a specific purpose.

```{r, echo=FALSE}
d_irpeatmodels <- 
  read.csv(system.file("extdata/models.csv", package = "irpeatmodels"))

d_models_to_variables <- 
  read.csv(system.file("extdata/models_to_variables.csv", package = "irpeat"))

dplyr::left_join(
  d_models_to_variables %>%
    dplyr::rename(model_name = "irpeatmodels_model_name"),
  d_irpeatmodels,
  by = c("model_name")
) %>%
  dplyr::mutate(irpeat_variable_name = paste0("`", irpeat_variable_name, "`")) %>%
  dplyr::relocate(irpeat_variable_name, .before = dplyr::everything()) %>%
  kableExtra::kable(
    col.names = c("Variable", "Model", "References", "Model description", "Model limitations", "Infrared mode", "Infrared range", "References (usage)", "References (limitations)")
  ) %>%
  kableExtra::kable_styling(
    bootstrap_options = c("striped", "condensed"),
    fixed_thead = TRUE
  ) %>%
  kableExtra::column_spec(4, width = "30em", width_min = "30em") %>%
  kableExtra::column_spec(8, width = "20em", width_min = "20em")
```










# Session info

```{r session-info, echo=FALSE}
sessionInfo()
```

# References

